from pathlib import Path

MAX_SENTENCE_SIZE = 100
SUBJECT_PATTERN = r"<SUBJECT>(.*)</SUBJECT>"
PREDICATE_PATTERN = r"<RELATION>(.*)</RELATION>"
OBJECT_PATTERN = r"<OBJECT>(.*)</OBJECT>"
SPECIAL_TOKEN_IDS = [101, 102, 0]
MODEL_DIR = Path("models")
PREDICATE_EXTRACTION_MODEL_DIR = MODEL_DIR / "predicate_extraction"
DEFAULT_MODEL_NAME = "default"
